from enum import Enum

class State(Enum):
    START = 1
    EXPECT_PROMPT_KEY = 2
    EXPECT_PROMPT = 3
    EXPECT_NAME_KEY = 4
    EXPECT_FUNCTION_NAME = 5
    EXPECT_PARAMETERS_KEY = 6
    EXPECT_PARAM_KEY = 7
    EXPECT_NUMBER = 8
    DONE = 9


NEXT_STATE = {
        State.START: State.EXPECT_PROMPT_KEY,
        State.EXPECT_PROMPT_KEY: State.EXPECT_PROMPT,
        State.EXPECT_PROMPT: State.EXPECT_NAME_KEY,
        State.EXPECT_NAME_KEY: State.EXPECT_FUNCTION_NAME,
        State.EXPECT_FUNCTION_NAME: State.EXPECT_PARAMETERS_KEY,
        State.EXPECT_PARAMETERS_KEY: State.EXPECT_PARAM_KEY,
        State.EXPECT_PARAM_KEY: State.EXPECT_NUMBER,
        State.EXPECT_NUMBER: State.DONE
}
