from enum import Enum

class State(Enum):
    START = 1
    EXPECT_NAME_KEY = 2
    EXPECT_FUNCTION_NAME = 3
    EXPECT_PARAMETERS_KEY = 4
    EXPECT_PARAM_KEY = 5
    EXPECT_NUMBER_START = 6
    EXPECT_NUMBER_CONT = 7
    DONE = 8


NEXT_STATE = {
        State.START: State.EXPECT_NAME_KEY,
        State.EXPECT_NAME_KEY: State.EXPECT_FUNCTION_NAME,
        State.EXPECT_FUNCTION_NAME: State.EXPECT_PARAMETERS_KEY,
        State.EXPECT_PARAMETERS_KEY: State.EXPECT_PARAM_KEY,
        State.EXPECT_PARAM_KEY: State.EXPECT_NUMBER_START,
        State.EXPECT_NUMBER_START: State.EXPECT_NUMBER_CONT,
        State.EXPECT_NUMBER_CONT: State.DONE
}
